Test primitive types:
  $ cat >test.ml <<EOF
  > external seek_in : in_channel -> int -> unit = "caml_ml_seek_in"
  > external seek_in_pair: in_channel * int -> unit = "caml_ml_seek_in_pair"
  > type int_endo = int -> int
  > external f : int_endo -> int_endo = "f"
  > external g : (int -> int) -> (int -> int) = "g"
  > EOF
  $ ocamlc -c -bin-annot test.ml
  $ lintcstubs_genmain test.cmt
  /* AUTOGENERATED FILE, DO NOT EDIT */
  #define CAML_NAME_SPACE
  #define _GNU_SOURCE
  #define _XOPEN_SOURCE 600
  #include <caml/mlvalues.h>
  CAMLprim value caml_ml_seek_in(value, value);
  CAMLprim value caml_ml_seek_in_pair(value);
  CAMLprim value f(value);
  CAMLprim value g(value, value);


