(*
 * Copyright (C) 2006-2009 Citrix Systems Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation; version 2.1 only. with the special
 * exception on linking described in file LICENSE.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *)

(** emergency mode, no access to the Db *)
type nodb = [`Emergency | `Removed]

(** regular mode *)
type db = [`DB]

(** it came from the coordinator, therefore we have access *)
type forwarded = db

type kind = [ db | nodb ]

(** A Context is used to represent every API invocation. It may be extended
    to include extra data without changing all the autogenerated signatures *)
type !+'a t constraint 'a = [< kind]

type origin = Http of Http.Request.t * Unix.file_descr | Internal

(** {6 Constructors} *)

val make :
     ?http_other_config:(string * string) list
  -> ?quiet:bool
  -> ?subtask_of:API.ref_task
  -> ?session_id:API.ref_session
  -> ?database:Xapi_database.Db_ref.t
  -> ?task_in_database:bool
  -> ?task_description:string
  -> ?origin:origin
  -> 'a
  -> string
  -> 'a t
(** [make ~__context ~subtask_of ~database ~session_id ~task_in_database ~task_description ~origin kind task_name] creates a new context.
    [http_other_config] are extra bits of context picked up from HTTP headers,
    [quiet] silences "task created" log messages,
    [subtask_of] is a reference to the parent task,
    [session_id] is the current session id,
    [database] is the database to use in future Db.* operations
    [origin] indicates whether the operation is triggered by an HTTP request or by an internal operation
    [task_in_database] indicates if the task needs to be stored the task in the database,
    [task_description] is the description of the task (Task.name_description),
    [kind] is the access kind to the database
    [task_name] is the task name of the created context (Task.name_label). *)

val of_http_req :
     ?session_id:API.ref_session
  -> ?internal_async_subtask:bool
  -> generate_task_for:bool
  -> supports_async:bool
  -> label:string
  -> http_req:Http.Request.t
  -> fd:Unix.file_descr
  -> kind
  -> kind t

val from_forwarded_task :
     ?http_other_config:(string * string) list
  -> ?session_id:API.ref_session
  -> ?origin:origin
  -> API.ref_task
  -> forwarded t

val make_subcontext : __context:'a t -> ?task_in_database:bool -> string -> 'a t

(** {6 Accessors} *)

val as_maybe_db: _ t -> [> db] t option
(** [as_maybe_db t] returns a Context that can access the database, or [None] if the current context doesn't have access. *)  

val as_no_db: _ t -> [> nodb] t
(** [as_no_db t] returns a Context that cannot access the database *)

val get_session_id : _ t -> API.ref_session
(** [get_session_id __context] returns the session id stored in [__context]. In case there is no session id in this
    context, it fails with [Failure "Could not find a session_id"]. *)

val get_task_id : _ t -> API.ref_task
(** [get_task_id __context] returns the task id stored in [__context]. Such a task can be either a task stored in
    database or a tempory task (also called dummy). *)

val forwarded_task : _ t -> bool

val string_of_task : _ t -> string

val string_of_task_and_tracing : _ t -> string

val tracing_of_dbg : string -> string * Tracing.Span.t option

val task_in_database : _ t -> bool
(** [task_in_database __context] indicates if [get_task_id __context] corresponds to a task stored in database or
    to a dummy task. *)

val get_origin : _ t -> string
(** [get_origin __context] returns a string containing the origin of [__context]. *)

val database_of : db t -> Xapi_database.Db_ref.t
(** [database_of __context] returns a database handle, which can be used by Db.* *)

(** {6 Destructors} *)

(* TODO: runtime check instead *)
val destroy : db t -> unit

(** {6 Auxiliary functions } *)

val is_unix_socket : Unix.file_descr -> bool
(** [is_unix_socket fd] *)

val preauth : __context:_ t -> [`root | `client_cert] option
(** [preauth ~__context] *)

val trackid_of_session :
  ?with_brackets:bool -> ?prefix:string -> API.ref_session option -> string

val trackid : ?with_brackets:bool -> ?prefix:string -> _ t -> string

val check_for_foreign_database : __context:([<db] as 'a) t -> 'a t

val get_http_other_config : Http.Request.t -> (string * string) list

(** {6 Functions which help resolving cyclic dependencies} *)

val __get_task_name : (__context:db t -> API.ref_task -> string) ref

val __destroy_task : (__context:db t -> API.ref_task -> unit) ref

val __make_task :
  (   __context:db t
   -> http_other_config:(string * string) list
   -> ?description:string
   -> ?session_id:API.ref_session
   -> ?subtask_of:API.ref_task
   -> string
   -> API.ref_task * [`task] Uuidx.t
  )
  ref

val set_test_rpc : _ t -> (Rpc.call -> Rpc.response) -> unit

val get_test_rpc : _ t -> (Rpc.call -> Rpc.response) option

val set_test_clusterd_rpc : _ t -> (Rpc.call -> Rpc.response) -> unit

val get_test_clusterd_rpc : _ t -> (Rpc.call -> Rpc.response) option

val get_client : _ t -> string option

val get_client_ip : _ t -> string option

val get_user_agent : _ t -> string option

val complete_tracing : ?error:exn * Printexc.raw_backtrace -> _ t -> unit

val tracing_of : _ t -> Tracing.Span.t option

val with_tracing :
  ?originator:string -> __context:'a t -> string -> ('a t -> 'b) -> 'b

val set_client_span : _ t -> Tracing.Span.t option
