name: Run OCaml C stub static analyzer on XAPI's C stubs

on:
  push:
  pull_request:
    branches:
      - master
      - 'feature/**'
      - '*-lcm'

jobs:
  ocaml-format:
    name: Ocaml files
    runs-on: ubuntu-22.04
    env:
      package: "xapi-lintcstubs"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull configuration from xs-opam
        run: |
          curl --fail --silent https://raw.githubusercontent.com/edwintorok/xs-opam/master/tools/xs-opam-ci.env | cut -f2 -d " " > .env

      - name: Load environment file
        id: dotenv
        uses: falti/dotenv-action@v1.0.2

      - name: Use ocaml
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-version: ${{ steps.dotenv.outputs.ocaml_version_full }}
          opam-repositories: ${{ steps.dotenv.outputs.repository }}
          dune-cache: true

      - name: Install dependencies for static analyzer
        run: |
          opam update
          opam pin add xapi-lintcstubs . --no-action
          opam install --deps-only ${{ env.package }}

      - name: Run static analyzer
        run: opam exec -- make analyze

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: _build/default/xapi.sarif
